language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - DJANGO_VERSION=Django==1.6
install:
  - pip install --use-mirrors $DJANGO_VERSION
  - python setup.py install 
script: nosetests
