language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - DJANGO=1.6 DJANGO_SETTINGS_MODULE=example.example.settings
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - python setup.py install 
script:
  - python example/manage.py test
